### PR TITLE
voter: only primary voter proposes and only once

### PR DESCRIPTION
**Pull request by andresilva**

### CODE REVIEW

**Comment by rphmeier** [comment]
We discussed this in the original PR and I was against including the `VoterId` in the voter at all. We haven't done it for any other messages either

**Comment by andresilva** [comment]
Sorry I missed that discussion. What if the local id is exposed from the `Environment`? I don't really want to spam consensus gossip with useless messages, and we either filter here or on substrate (which means the logic for primary election leaks there).

**Comment by rphmeier** [comment]
Yeah, although it does seem like a somewhat debatable point. I think we either go all-the-way with `VoterId` in `finality-grandpa` or not at all. So if `Id` is `None` we don't send messages at all, for instance.

**Comment by rphmeier** [comment]
@andresilva 

> we either filter here or on substrate (which means the logic for primary election leaks there).

The idea is that with https://github.com/paritytech/finality-grandpa/issues/55 we will just call `voter_state.round_data(round).primary == self.id` for filtering -- the logic for primary election doesn't need to leak.

**Comment by andresilva** [comment]
I agree that doing the filtering on substrate is more inline with what we have now, especially with #55. I'll update this PR shortly to remove this.

**Comment by andresilva** [comment]
After discussing this with @rphmeier we've decided to go "all-in" on using the `voter_id` and move the logic for filtering messages to this crate. I've updated the PR so that no votes are sent out if we're not a current voter in the voter set. The local voter id is given per-round through `Environment::round_data`. The protocol state machine still transitions as if the votes were cast, the only difference being that we don't push the messages to the sink. Commits are still pushed out and should be filtered on substrate side (although it may be beneficial in some cases for observers to broadcast commits).

**Pull request merged**
